### ISSUE TITLE
屏蔽的标签过多,后面添加的标签会失效

### ISSUE THREAD

**Issue by ACodeHX** [tjxwork/bilibili_blocked_videos_by_tags#10]
我屏蔽的标签大概有 80 多个,有次屏蔽的时候发现没有屏蔽含该标签的视频,但是屏蔽 up 主的名字就可以屏蔽,所以不支持大多的标签吗,还是出 bug 了.

游览器:Chromium 105.0.5195.127
插件版本:1.1.5

**Comment by tjxwork** [comment]
提供一下标签列表，和失效的视频BV

**Comment by ACodeHX** [comment]
这个 bug 有时就会出现,比如这个视频 BV1T5UTYtEmj ,我屏蔽了`财经商业`但页面还是会出现,添加视频的另一个标签`买房`后就被屏蔽了,

[Flags-list.txt](https://github.com/user-attachments/files/17759020/Flags-list.txt)

**Comment by ACodeHX** [comment]
感觉可以换个标题，应该是有些屏蔽的标签没有生效

**Comment by ACodeHX** [comment]
是 chrome 120.0.6099.130 游览器会出现添加屏蔽标签,视频没有屏蔽

屏蔽的标签为:自驾317,开着挖机游全国,但是视频没有屏蔽 BV152SQYTEyc

[Flags-list.txt](https://github.com/user-attachments/files/17768920/Flags-list.txt)

**Comment by tjxwork** [comment]
根据你提供的屏蔽列表和BV视频，我这边能正常屏蔽，尝试打开日志输出，看一下控制台有没有输出报错信息。

![QQ截图20241115145613](https://github.com/user-attachments/assets/ae6fc7d9-1f44-46b0-82f3-3d58a27de2d4)

**Comment by ACodeHX** [comment]
我发现是`空格`标签造成的错误,去掉就可以屏蔽了

![flags1](https://github.com/user-attachments/assets/3816a42e-cf2c-4b88-b30f-6c6e4add899f)
