### ISSUE TITLE
添加一个拖动UI窗口的函数

### ISSUE THREAD

**Issue by a11034** [tjxwork/bilibili_blocked_videos_by_tags#5]
```javascript
function makeDraggable(element) {
    let isDragging = false;
    let offsetX, offsetY;

    element.addEventListener('mousedown', (e) => {
        if (e.target.constructor.name !== 'HTMLTextAreaElement' &&e.target.constructor.name !== 'HTMLInputElement')
        {
            isDragging = true;
            const rect = element.getBoundingClientRect();
            offsetX = e.clientX - rect.left;
            offsetY = e.clientY - rect.top;
            element.style.cursor = 'grabbing';
            element.style.transform = '';
            e.preventDefault();
        }
    });

    document.addEventListener('mousemove', (e) => {
        if (isDragging) {
            // 直接使用mouse的位置减去偏移量设置元素位置
            element.style.left = `${e.clientX - offsetX}px`;
            element.style.top = `${e.clientY - offsetY}px`;
        }
    });

    document.addEventListener('mouseup', () => {
        isDragging = false;
        element.style.cursor = 'default';
    });
}
```

**Comment by a11034** [comment]
![image](https://github.com/tjxwork/bilibili_blocked_videos_by_tags/assets/111724924/6ccc376b-2f41-4951-aa3a-e9982e222c30)
窗口可以被反复唤出。样式是另改的。

**Comment by a11034** [comment]
![image](https://github.com/tjxwork/bilibili_blocked_videos_by_tags/assets/111724924/cfbee4bf-43c2-4e41-918e-87d4c2f7bd77)
![image](https://github.com/tjxwork/bilibili_blocked_videos_by_tags/assets/111724924/df1f6c95-a996-4654-8a49-930d91a566e9)
![image](https://github.com/tjxwork/bilibili_blocked_videos_by_tags/assets/111724924/c948dc35-9370-422f-9b2b-903bd86b9ef3)
不会PullRequest，抱歉。

**Comment by tjxwork** [comment]
我GitHub也不怎么会用……

关于UI，我打算改，但是没什么好思路，现在的UI硬是手写堆出来的屎山。

能滚动的确是最简单的解决方法。

拖动窗口这想法我还真没想过，我这个菜鸡，拖动窗口的代码看不看得懂我都没保证。
我大概暂时不会采取这个方法。

重复唤出的问题……
我想了一下，又翻了一下代码……
是正常的。
因为我根本就没做存在判断，忘记测试用户多次唤出这种情况了。
而且原来毕竟位置是固定的，就算点多了是在一个位置，一眼看不出来问题。

重复唤出下次更新再解决吧。

**Comment by tjxwork** [comment]
v1.0.0 UI重构，已经修复窗口问题。
