### ISSUE TITLE
与 bv2av 同时使用时排行榜页面屏蔽失效

### ISSUE THREAD

**Issue by Henry-ZHR** [tjxwork/bilibili_blocked_videos_by_tags#7]
bv2av: <https://greasyfork.org/zh-CN/scripts/398535-bv2av>

**Comment by Henry-ZHR** [comment]
bv2av 应该是把 href 标签换了，然后脚本只识别 bv 号不管 av 号？

我还以为搜索界面没事 但是好像也有事 看起来没事只是因为没来得及换？

**Comment by tjxwork** [comment]
合并了，等一下更新一下版本号和感谢(doge)。

至于这个bv2av……
屏蔽脚本核心机制就是BV号，要想修复这个兼容性，我还得bv2av替换完的AV号转回来。
暂时不知道怎么转换的，有空再说吧……

**Comment by Henry-ZHR** [comment]
av->bv https://socialsisteryi.github.io/bilibili-API-collect/docs/misc/bvid_desc.html

**Comment by Henry-ZHR** [comment]
虽然没得抄代码但是应该写得够清楚了？

**Comment by tjxwork** [comment]
bv2av在兼容已经做好了，测试的时候发现播放页的叠加层不正常。
我现在才想起来为什么当时不直接定义成100%或者top:0之类 ，而是硬去读父元素的大小……

**Comment by tjxwork** [comment]
v1.1.3 兼容脚本处理：bv2av(此脚本会将视频链接替换为旧的 AV 号链接)，感谢 @Henry-ZHR 的提出；
不完善功能修复：每次触发运行时，会将屏蔽叠加背景层与父元素尺寸进行同步，解决了页面布局变化时叠加层不跟随变化，感谢 @Henry-ZHR 的建议；
“隐藏首页等页面的非视频元素” 功能生效范围增加：隐藏 搜索页——综合 下的 直播卡片；

**Comment by Henry-ZHR** [comment]
不好意思 我视频播放页的推荐栏都屏蔽掉了 没发现有问题。。。

**Comment by Henry-ZHR** [comment]
![](https://github.com/tjxwork/bilibili_blocked_videos_by_tags/assets/51886614/8ec76a6a-02f9-43c9-b2de-0d71d44c1862)

然后对应的元素是包含整个推荐栏的祖先 就寄了

评价为：![](https://github.com/tjxwork/bilibili_blocked_videos_by_tags/assets/51886614/c1766096-c9c1-48e8-83f0-ca6d7ffaf79b)
